# -*- coding: utf-8 -*-
"""CAT and DOG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amarSh41un7aHCXgbH_w09qvdhyexuSs
"""

# -- Imports --
import streamlit as st
import numpy as np
import os
import urllib.request
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from PIL import Image

st.set_page_config(page_title="Cat vs Dog Classifier", layout="centered")
MODEL_PATH = "CAT_DOG_model.h5"
IMG_SIZE = (150, 150)
CLASS_NAMES = ['Cat', 'Dog']

@st.cache_resource
def load_local_model():
    model = load_model(MODEL_PATH)
    return model

model = load_local_model()

# -- UI Styling --
st.markdown("""
    <style>
        .stButton>button {
            background-color: #007bff;
            color: white;
            font-weight: bold;
            border-radius: 5px;
        }
        .stButton>button:hover {
            background-color: #0056b3;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #888;
            font-size: 0.85rem;
        }
    </style>
""", unsafe_allow_html=True)

# -- App Title and Upload --
st.title("🐱🐶 Cat vs Dog Classifier")
st.markdown("Upload an image to determine whether it's a **cat** or a **dog**.")

uploaded_file = st.file_uploader("📤 Upload an image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file).convert('RGB')
    st.image(img, caption="Uploaded Image", use_column_width=False, width=300)

    # Preprocess
    img_resized = img.resize(IMG_SIZE)
    img_array = image.img_to_array(img_resized) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    with st.spinner("🔍 Classifying..."):
        prediction = model.predict(img_array)[0]
        predicted_class = CLASS_NAMES[int(round(prediction[0]))]  # Assuming output is a sigmoid score
        confidence = prediction[0] * 100 if predicted_class == 'Dog' else (1 - prediction[0]) * 100

    # Display Results
    st.success(f"🎯 **Prediction:** `{predicted_class}`")
    st.metric("🔒 Confidence", f"{confidence:.2f} %")

from google.colab import files
uploaded = files.upload()